### ISSUE TITLE
OpenWRT Installation Issue

### ISSUE THREAD

**Issue by micpro7** [daniel0076/docker-megasync-arm#1]
having issues installing this inside OpenWRT on a NanoPi R4S with Docker CE Enabled 

docker: Error response from daemon: manifest for daniel0076/megasync-arm:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

daniel0076/docker-megasync-arm & daniel0076/megasync-arm does not work

**Comment by daniel0076** [comment]
Hi @micpro7 

It seems that the issue is related to the tag you use to download the docker image, and I think you got those errors simply because I didn't tag my image with `latest`.

Please try with `docker pull daniel0076/megasync-arm:aarch64-v0.1`

**Comment by micpro7** [comment]
Thanks worked perfectly
